import { Artwork, Category, Order, PaymentMethod, GallerySettings } from '../../types';

export const INITIAL_SETTINGS: GallerySettings = {
  gallery_name: 'KAYOLA',
  tagline_fr: 'Art Contemporain',
  tagline_en: 'Contemporary Art',
  logo_url: '',
  logo_type: 'monogram',
  contact_email: 'contact@kayola-art.com',
  contact_phone: '+509 3800-0000',
  address: 'KAYOLA Space, Port-au-Prince & Global Concierge',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'peinture',
    name_fr: 'Peinture Contemporaine',
    name_en: 'Contemporary Painting',
    description_fr: 'Huiles, acryliques et toiles texturales aux pigments vibrants.',
    description_en: 'Oils, acrylics, and textural canvases with vibrant pigments.',
    image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-2',
    slug: 'sculpture',
    name_fr: 'Sculpture & Volume',
    name_en: 'Sculpture & Volume',
    description_fr: 'Créations en bronze, pierre, céramique et matériaux nobles.',
    description_en: 'Creations in bronze, stone, ceramic, and noble materials.',
    image_url: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-3',
    slug: 'photographie',
    name_fr: 'Photographie d’Art',
    name_en: 'Fine Art Photography',
    description_fr: 'Tirages argentiques et impressions digigraphiques limitées.',
    description_en: 'Silver gelatin prints and limited digigraph prints.',
    image_url: 'https://images.unsplash.com/photo-1554080353-a576cf803bda?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-4',
    slug: 'art-numerique',
    name_fr: 'Art Numérique & Hybride',
    name_en: 'Digital & Hybrid Art',
    description_fr: 'Explorations visuelles génératives et compositions immersives.',
    description_en: 'Generative visual explorations and immersive compositions.',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-5',
    slug: 'techniques-mixtes',
    name_fr: 'Techniques Mixtes',
    name_en: 'Mixed Media',
    description_fr: 'Collages, matières superposées et expérimentations plastiques.',
    description_en: 'Collages, layered mediums, and plastic experimentations.',
    image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_ARTWORKS: Artwork[] = [
  {
    id: 'art-1',
    item_code: 'ART-2026-001',
    slug: 'the-blue-horizon',
    title_fr: 'The Blue Horizon',
    title_en: 'The Blue Horizon',
    artist: 'Damien Kael',
    artist_bio_fr: 'Damien Kael explore les confins marins et les étendues atmosphériques à travers des empâtements riches et une lumière méditative.',
    artist_bio_en: 'Damien Kael explores maritime depths and atmospheric expanses through rich impastos and meditative light.',
    description_fr: 'Une œuvre monumentale évoquant la rencontre entre l’océan profond et le firmament au crépuscule. Les touches de bleu outremer et d’or créent une vibration hypnotique sous la lumière naturelle.',
    description_en: 'A monumental artwork evoking the union between deep ocean and the dusk firmament. Notes of ultramarine and subtle gold create a hypnotic resonance under natural light.',
    price: 3400,
    currency: 'USD',
    category_id: 'cat-1',
    technique_fr: 'Huile sur lin brut et feuille d’or',
    technique_en: 'Oil on raw linen with gold leaf',
    materials_fr: 'Pigments purs, huile de lin, feuille d’or 24k, châssis bois massif',
    materials_en: 'Pure pigments, linseed oil, 24k gold leaf, solid wood frame',
    year: 2026,
    width_cm: 120,
    height_cm: 90,
    depth_cm: 4.5,
    weight_kg: 6.2,
    is_framed: true,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-1-1',
        artwork_id: 'art-1',
        url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Vue principale The Blue Horizon',
        alt_text_en: 'Primary view of The Blue Horizon',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-1-2',
        artwork_id: 'art-1',
        url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Détail des textures et feuille d’or',
        alt_text_en: 'Texture detail and gold leaf close-up',
        sort_order: 2,
      },
      {
        id: 'img-1-3',
        artwork_id: 'art-1',
        url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Mise en situation dans salon de collectionneur',
        alt_text_en: 'Interior staging in a collector living space',
        sort_order: 3,
      },
    ],
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'art-2',
    item_code: 'ART-2026-002',
    slug: 'golden-reverie',
    title_fr: 'Golden Reverie',
    title_en: 'Golden Reverie',
    artist: 'Isabella Moreau',
    artist_bio_fr: 'Diplômée des Beaux-Arts, Isabella conjugue architecture coloniale et abstractions chromatiques éclatantes.',
    artist_bio_en: 'Beaux-Arts graduate Isabella marries colonial architectural silhouettes with radiant chromatic abstraction.',
    description_fr: 'Une ode aux façades historiques baignées par une lumière solaire incandescente. La composition joue avec les contrastes chaleureux et les aplats architecturaux.',
    description_en: 'An ode to historic facades bathed in incandescent sunlight. The composition balances warm architectural contrasts with luminous color blocks.',
    price: 2850,
    currency: 'USD',
    category_id: 'cat-1',
    technique_fr: 'Acrylique et encres de Chine sur toile de coton',
    technique_en: 'Acrylic and India ink on heavy cotton canvas',
    materials_fr: 'Acrylique extra-fine, encre permanente, vernis mat anti-UV',
    materials_en: 'Extra-fine acrylic, permanent ink, anti-UV matte varnish',
    year: 2026,
    width_cm: 100,
    height_cm: 100,
    depth_cm: 4,
    weight_kg: 5.0,
    is_framed: true,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-2-1',
        artwork_id: 'art-2',
        url: 'https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Golden Reverie par Isabella Moreau',
        alt_text_en: 'Golden Reverie by Isabella Moreau',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-2-2',
        artwork_id: 'art-2',
        url: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Angle et texture Golden Reverie',
        alt_text_en: 'Side angle and texture for Golden Reverie',
        sort_order: 2,
      },
    ],
    created_at: '2026-08-12T14:30:00Z',
  },
  {
    id: 'art-3',
    item_code: 'ART-2026-003',
    slug: 'echoes-of-the-forgotten',
    title_fr: 'Echoes of the Forgotten',
    title_en: 'Echoes of the Forgotten',
    artist: 'Damien Kael',
    artist_bio_fr: 'Figure majeure du portrait contemporain introspectif, explorant la mémoire collective et le regard humain.',
    artist_bio_en: 'Major contemporary portraitist probing human gaze, ancestral memories, and emotional depth.',
    description_fr: 'Un portrait expressif saisissant, sculpté dans la matière picturale. L’intensité du regard interpelle le spectateur et transcende le temps.',
    description_en: 'A striking expressive portrait carved into layered impasto. The intensity of the gaze engages the viewer and transcends temporal boundaries.',
    price: 4200,
    currency: 'USD',
    category_id: 'cat-1',
    technique_fr: 'Huile et pigments naturels au couteau',
    technique_en: 'Oil and raw pigments with palette knife',
    materials_fr: 'Huile fine, cire d’abeille, toile tendue sur châssis à clés',
    materials_en: 'Fine oil, beeswax medium, Belgian linen on keyed stretcher',
    year: 2025,
    width_cm: 80,
    height_cm: 110,
    depth_cm: 3.8,
    weight_kg: 4.8,
    is_framed: false,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-3-1',
        artwork_id: 'art-3',
        url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Echoes of the Forgotten portrait',
        alt_text_en: 'Echoes of the Forgotten portrait view',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-3-2',
        artwork_id: 'art-3',
        url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Détail de la matière et du regard',
        alt_text_en: 'Close-up of texture and gaze',
        sort_order: 2,
      },
    ],
    created_at: '2026-08-01T09:15:00Z',
  },
  {
    id: 'art-4',
    item_code: 'ART-2026-004',
    slug: 'ephemeral-bloom',
    title_fr: 'Ephemeral Bloom',
    title_en: 'Ephemeral Bloom',
    artist: 'Nadia Laurent',
    artist_bio_fr: 'Nadia Laurent fusionne la poésie botanique et les voyages oniriques à travers des compositions riches en symbolisme.',
    artist_bio_en: 'Nadia Laurent merges botanical poetry and dreamlike voyages through rich symbolic compositions.',
    description_fr: 'Une fresque figurative où la majesté d’un éléphant d’apparat se mêle aux floraisons éclatantes et aux drapés pourpres.',
    description_en: 'A figurative masterwork where the solemn majesty of a ceremonial elephant intertwines with vibrant flora and crimson drapery.',
    price: 3800,
    currency: 'USD',
    category_id: 'cat-5',
    technique_fr: 'Aquarelle sur papier Arches et rehaussé de gouache',
    technique_en: 'Watercolor on Arches 640g paper with gouache highlights',
    materials_fr: 'Papier pur coton 640g, aquarelle extra-fine, verre musée anti-reflet',
    materials_en: '640g pure cotton paper, extra-fine watercolor, museum anti-reflective glass',
    year: 2026,
    width_cm: 95,
    height_cm: 75,
    depth_cm: 3,
    weight_kg: 3.5,
    is_framed: true,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-4-1',
        artwork_id: 'art-4',
        url: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Ephemeral Bloom par Nadia Laurent',
        alt_text_en: 'Ephemeral Bloom by Nadia Laurent',
        sort_order: 1,
        is_primary: true,
      },
    ],
    created_at: '2026-08-15T11:20:00Z',
  },
  {
    id: 'art-5',
    item_code: 'ART-2026-005',
    slug: 'the-shimmering-tides',
    title_fr: 'The Shimmering Tides',
    title_en: 'The Shimmering Tides',
    artist: 'Nadia Laurent',
    artist_bio_fr: 'Artiste explorant les flux aquatiques et les mouvements topographiques vus du ciel.',
    artist_bio_en: 'Artist exploring aquatic currents and topographic patterns viewed from high altitudes.',
    description_fr: 'Une vue aérienne abstraite inspirée des lagons turquoise et des bancs de sable dorés. L’équilibre des tonalités invite au calme et à l’évasion.',
    description_en: 'An aerial abstract perspective inspired by turquoise lagoons and sunlit sandbars. The tonal equilibrium invites serenity and quiet wonder.',
    price: 3100,
    currency: 'USD',
    category_id: 'cat-4',
    technique_fr: 'Résine époxy pigmentée et encres métalliques sur panneau de bois',
    technique_en: 'Pigmented epoxy resin and metallic inks on cradled wood panel',
    materials_fr: 'Résine cristal bio-sourcée, mica doré, pigments marins, panneau bouleau',
    materials_en: 'Bio-based crystal resin, gold mica, marine pigments, birch panel',
    year: 2026,
    width_cm: 110,
    height_cm: 80,
    depth_cm: 5,
    weight_kg: 7.1,
    is_framed: false,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-5-1',
        artwork_id: 'art-5',
        url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'The Shimmering Tides vue d’ensemble',
        alt_text_en: 'The Shimmering Tides full overview',
        sort_order: 1,
        is_primary: true,
      },
    ],
    created_at: '2026-08-18T16:45:00Z',
  },
  {
    id: 'art-6',
    item_code: 'ART-2026-006',
    slug: 'keeper-of-the-night',
    title_fr: 'Keeper of the Night',
    title_en: 'Keeper of the Night',
    artist: 'Robbie Arnett',
    artist_bio_fr: 'Peintre symboliste contemporain créant des paysages nocturnes illuminés par des apparitions dorées.',
    artist_bio_en: 'Contemporary symbolist painter composing nocturnal landscapes illuminated by gilded apparitions.',
    description_fr: 'Un cerf d’or se dresse sous la lune ronde au milieu de monts aux teintes sombres et ocres. Une allégorie de la vigilance et de la noblesse d’esprit.',
    description_en: 'A golden stag stands poised under a luminescent moon amidst dark ochre valleys. A visual allegory of quiet resilience and noble vigilance.',
    price: 4600,
    currency: 'USD',
    category_id: 'cat-1',
    technique_fr: 'Huile et laque japonaise sur toile de lin',
    technique_en: 'Oil and Japanese urushi lacquer on Belgian linen',
    materials_fr: 'Pigments nocturnes, poudre d’or, laque végétale, cadre en noyer massif',
    materials_en: 'Night pigments, gold powder, organic lacquer, solid walnut frame',
    year: 2025,
    width_cm: 130,
    height_cm: 100,
    depth_cm: 5,
    weight_kg: 8.0,
    is_framed: true,
    has_certificate: true,
    featured: true,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-6-1',
        artwork_id: 'art-6',
        url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Keeper of the Night',
        alt_text_en: 'Keeper of the Night artwork',
        sort_order: 1,
        is_primary: true,
      },
    ],
    created_at: '2026-07-28T12:00:00Z',
  },
  {
    id: 'art-7',
    item_code: 'ART-2026-007',
    slug: 'leveil-sculptural',
    title_fr: 'L’Éveil Sculptural',
    title_en: 'The Sculptural Awakening',
    artist: 'Marc-Aurèle Saint-Jean',
    artist_bio_fr: 'Sculpteur renommé travaillant la tension entre les formes anthropomorphiques et la force brute du bronze.',
    artist_bio_en: 'Renowned sculptor exploring tension between anthropomorphic gestures and the primal weight of bronze.',
    description_fr: 'Buste sculpté avec une puissance brute, révélant la texture du plâtre et l’empreinte des mains du maître.',
    description_en: 'Sculptural bust formed with raw elemental vigor, unveiling textured patina and the direct touch of the sculptor’s hands.',
    price: 5200,
    currency: 'USD',
    category_id: 'cat-2',
    technique_fr: 'Bronze à la cire perdue, patine brune et reflets chauds',
    technique_en: 'Lost-wax cast bronze, warm brown patina',
    materials_fr: 'Bronze d’art, socle en marbre noir de carrare',
    materials_en: 'Fine art bronze, black Carrara marble base',
    year: 2026,
    width_cm: 45,
    height_cm: 65,
    depth_cm: 35,
    weight_kg: 18.5,
    is_framed: false,
    has_certificate: true,
    featured: false,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-7-1',
        artwork_id: 'art-7',
        url: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'L’Éveil Sculptural en bronze',
        alt_text_en: 'Sculptural Awakening in bronze',
        sort_order: 1,
        is_primary: true,
      },
    ],
    created_at: '2026-08-05T08:00:00Z',
  },
  {
    id: 'art-8',
    item_code: 'ART-2026-008',
    slug: 'solitude-urbaine',
    title_fr: 'Solitude Urbaine sous la Pluie',
    title_en: 'Urban Solitude in Rain',
    artist: 'Claire Delacroix',
    artist_bio_fr: 'Photographe documentant la poésie des grandes métropoles à travers le prisme des reflets et de la pénombre.',
    artist_bio_en: 'Fine art photographer documenting metropolitan soul through luminous reflections and soft twilight.',
    description_fr: 'Tirage d’art d’une promenade solitaire sous les parapluies illuminés par les réverbères d’une allée pavée.',
    description_en: 'Fine art photographic print capturing a solitary stroll beneath umbrellas, mirrored in rain-drenched cobblestones.',
    price: 1950,
    currency: 'USD',
    category_id: 'cat-3',
    technique_fr: 'Tirage argentique baryté signé et numéroté 1/1',
    technique_en: 'Baryta silver gelatin print signed and numbered 1/1',
    materials_fr: 'Papier Hahnemühle Photo Rag 308g, encres pigmentaires UltraChrome',
    materials_en: 'Hahnemühle Photo Rag 308g, UltraChrome archival pigment inks',
    year: 2025,
    width_cm: 80,
    height_cm: 60,
    depth_cm: 2.5,
    weight_kg: 3.0,
    is_framed: true,
    has_certificate: true,
    featured: false,
    status: 'SOLD',
    sold_at: '2026-08-20T17:30:00Z',
    images: [
      {
        id: 'img-8-1',
        artwork_id: 'art-8',
        url: 'https://images.unsplash.com/photo-1554080353-a576cf803bda?auto=format&fit=crop&w=1200&q=85',
        alt_text_fr: 'Solitude Urbaine sous la Pluie',
        alt_text_en: 'Urban Solitude in Rain',
        sort_order: 1,
        is_primary: true,
      },
    ],
    created_at: '2026-07-15T15:00:00Z',
  },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 'pay-moncash',
    name: 'MonCash (Paiement Mobile)',
    type: 'moncash',
    description_fr: 'Paiement instantané via votre compte MonCash (Digicel).',
    description_en: 'Instant mobile transfer via your MonCash account (Digicel).',
    instructions_fr: 'Effectuez le transfert MonCash vers le numéro ci-dessous avec le numéro de commande en référence, puis téléversez une capture de la transaction.',
    instructions_en: 'Send the MonCash transfer to the number below with your Order # as reference, then upload your confirmation screenshot.',
    account_name: 'GALERIE KAYOLA S.A.',
    account_number: '+509 3812-4455',
    phone_number: '+509 3812-4455',
    additional_information_fr: 'Frais de transfert habituels à la charge de l’acheteur. Validation sous 2h.',
    additional_information_en: 'Standard mobile fees apply. Verified by our curator within 2 hours.',
    logo_url: 'https://images.unsplash.com/photo-1556742049-0a67e5572263?auto=format&fit=crop&w=300&q=80',
    is_active: true,
  },
  {
    id: 'pay-natcash',
    name: 'NatCash (Paiement Mobile)',
    type: 'natcash',
    description_fr: 'Paiement mobile sécurisé via NatCash (Natcom).',
    description_en: 'Secure mobile payment via NatCash (Natcom).',
    instructions_fr: 'Effectuez le versement sur le compte NatCash marchand ci-dessous et conservez le SMS de confirmation pour le téléversement.',
    instructions_en: 'Send payment to the NatCash merchant account below and keep the SMS receipt for proof upload.',
    account_name: 'KAYOLA ART EXCLUSIF',
    account_number: '+509 4233-8899',
    phone_number: '+509 4233-8899',
    additional_information_fr: 'Service disponible 24/7.',
    additional_information_en: 'Available 24/7.',
    logo_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=300&q=80',
    is_active: true,
  },
  {
    id: 'pay-sogebank',
    name: 'Virement Bancaire — Sogebank (USD / HTG)',
    type: 'bank_transfer',
    description_fr: 'Virement de compte à compte ou dépôt en succursale Sogebank.',
    description_en: 'Direct bank transfer or branch deposit at Sogebank.',
    instructions_fr: 'Initiez un virement bancaire vers notre compte courant Sogebank. Mentionnez impérativement votre Nom et le Numéro de Commande.',
    instructions_en: 'Initiate a bank transfer to our Sogebank checking account. State your Name and Order # in the reference field.',
    account_name: 'KAYOLA CONTEMPORARY ART INC',
    account_number: '210-0987-65432-01 (USD)',
    additional_information_fr: 'IBAN / Routing : SOGEHTPPXXX — Agence Pétion-Ville',
    additional_information_en: 'Swift / Routing : SOGEHTPPXXX — Petion-Ville Branch',
    logo_url: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?auto=format&fit=crop&w=300&q=80',
    is_active: true,
  },
  {
    id: 'pay-unibank',
    name: 'Virement Bancaire — Unibank (USD / HTG)',
    type: 'bank_transfer',
    description_fr: 'Virement Unibank en ligne ou en agence.',
    description_en: 'Unibank online wire or branch transaction.',
    instructions_fr: 'Transférez le montant exact sur notre compte Unibank. Téléversez le bordereau de versement ou la confirmation PDF.',
    instructions_en: 'Transfer exact amount to our Unibank account. Upload the deposit slip or PDF confirmation.',
    account_name: 'KAYOLA CONTEMPORARY ART INC',
    account_number: '140-5567-89101-02 (USD)',
    additional_information_fr: 'Code Swift : UNIBHTPP',
    additional_information_en: 'Swift Code: UNIBHTPP',
    logo_url: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&w=300&q=80',
    is_active: true,
  },
  {
    id: 'pay-wire',
    name: 'International Wire Transfer (SWIFT / Fedwire)',
    type: 'wire',
    description_fr: 'Virement international pour les collectionneurs hors-territoire.',
    description_en: 'International wire transfer for global art collectors.',
    instructions_fr: 'Effectuez un virement international SWIFT vers notre banque dépositaire. Prévoyez 24 à 48h de délai de réception.',
    instructions_en: 'Send an international SWIFT wire transfer to our depository bank. Processing takes 24 to 48 hours.',
    account_name: 'KAYOLA GLOBAL ART HOLDINGS LLC',
    account_number: 'US89-CITI-0210-0008-9482-11',
    additional_information_fr: 'Banque : Citibank N.A. New York — SWIFT : CITIUS33XXX',
    additional_information_en: 'Bank: Citibank N.A. New York — SWIFT: CITIUS33XXX',
    logo_url: 'https://images.unsplash.com/photo-1616077168079-7e09a677fb2c?auto=format&fit=crop&w=300&q=80',
    is_active: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-demo-1',
    order_number: 'ART-2026-00124',
    tracking_token: 'kayola-sec-7f9a2e1d88bc4a',
    access_code: '482917',
    artwork_id: 'art-1',
    artwork: INITIAL_ARTWORKS[0],
    customer_first_name: 'Jean-Philippe',
    customer_last_name: 'Duval',
    customer_email: 'jp.duval@collection-art.com',
    customer_phone: '+509 3712-9900',
    customer_address: '14 Rue des Palmiers, Bois-Verna',
    customer_city: 'Port-au-Prince',
    customer_country: 'Haïti',
    customer_notes: 'Livraison sécurisée avec certificat signé.',
    payment_method_id: 'pay-sogebank',
    payment_method: INITIAL_PAYMENT_METHODS[2],
    amount: 3400,
    currency: 'USD',
    status: 'PAYMENT_REVIEW',
    payment_submitted_at: '2026-08-23T14:15:00Z',
    created_at: '2026-08-23T14:02:00Z',
    updated_at: '2026-08-23T14:15:00Z',
    payment_proofs: [
      {
        id: 'prf-1',
        order_id: 'ord-demo-1',
        file_name: 'recu_virement_sogebank_duval.png',
        file_type: 'image/png',
        file_size: 342000,
        file_data_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
        uploaded_at: '2026-08-23T14:15:00Z',
        status: 'PENDING',
      },
    ],
    events: [
      {
        id: 'evt-1',
        order_id: 'ord-demo-1',
        event_type: 'ORDER_CREATED',
        description_fr: 'Commande initiée par le client (Guest Checkout).',
        description_en: 'Order initiated by client (Guest Checkout).',
        created_at: '2026-08-23T14:02:00Z',
      },
      {
        id: 'evt-2',
        order_id: 'ord-demo-1',
        event_type: 'PROOF_UPLOADED',
        description_fr: 'Preuve de virement Sogebank soumise par le client.',
        description_en: 'Sogebank transfer proof submitted by client.',
        created_at: '2026-08-23T14:15:00Z',
      },
    ],
  },
  {
    id: 'ord-demo-2',
    order_number: 'ART-2026-00098',
    tracking_token: 'kayola-sec-3a1b8c9d4e5f60',
    access_code: '194826',
    artwork_id: 'art-8',
    artwork: INITIAL_ARTWORKS[7],
    customer_first_name: 'Eleonore',
    customer_last_name: 'Bastien',
    customer_email: 'eleonore.bastien@luxury.fr',
    customer_phone: '+33 6 44 20 18 90',
    customer_address: '22 Avenue Montaigne',
    customer_city: 'Paris',
    customer_country: 'France',
    customer_notes: 'Emballage d’art renforcé pour transport aérien.',
    payment_method_id: 'pay-wire',
    payment_method: INITIAL_PAYMENT_METHODS[4],
    amount: 1950,
    currency: 'USD',
    status: 'SOLD',
    payment_submitted_at: '2026-08-19T10:00:00Z',
    payment_verified_at: '2026-08-20T11:00:00Z',
    sold_at: '2026-08-20T17:30:00Z',
    created_at: '2026-08-19T09:30:00Z',
    updated_at: '2026-08-20T17:30:00Z',
    payment_proofs: [
      {
        id: 'prf-2',
        order_id: 'ord-demo-2',
        file_name: 'swift_transfer_bastien.pdf',
        file_type: 'application/pdf',
        file_size: 458000,
        file_data_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
        uploaded_at: '2026-08-19T10:00:00Z',
        status: 'ACCEPTED',
        reviewed_at: '2026-08-20T11:00:00Z',
        reviewed_by: 'Commissaire Principal',
      },
    ],
    events: [
      {
        id: 'evt-2-1',
        order_id: 'ord-demo-2',
        event_type: 'ORDER_CREATED',
        description_fr: 'Commande enregistrée.',
        description_en: 'Order created.',
        created_at: '2026-08-19T09:30:00Z',
      },
      {
        id: 'evt-2-2',
        order_id: 'ord-demo-2',
        event_type: 'PAYMENT_ACCEPTED',
        description_fr: 'Paiement SWIFT vérifié et validé par la galerie.',
        description_en: 'SWIFT payment verified and approved by gallery.',
        created_at: '2026-08-20T11:00:00Z',
      },
      {
        id: 'evt-2-3',
        order_id: 'ord-demo-2',
        event_type: 'SALE_CONFIRMED',
        description_fr: 'Vente officiellement confirmée. Œuvre vendue.',
        description_en: 'Sale officially confirmed. Artwork marked as SOLD.',
        created_at: '2026-08-20T17:30:00Z',
      },
    ],
  },
];